app/blog/views/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function, unicode_literals, absolute_import
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SubmitField
from wtforms.validators import DataRequired, Length, Email
from wtforms import ValidationError
from flask_pagedown.fields import PageDownField
from ..models import Role, User, Category


class NameForm(FlaskForm):
    name = StringField('你的名字是什么？', validators=[DataRequired()])
    submit = SubmitField('提交')


# 这个表单中的所有字段都是可选的,因此长度验证函数允许长度为零
class EditProfileForm(FlaskForm):
    name = StringField('真实姓名', validators=[Length(0,64)])
    location = StringField('地点', validators=[Length(0,64)])
    about_me = TextAreaField('关于我')
    submit = SubmitField('提交')


class EditProfileAdminForm(FlaskForm):
    email = StringField('邮箱', validators=[DataRequired(), Length(1, 64), Email()])
    username = StringField('用户名', validators=[DataRequired(), Length(1, 64)])
    # confirmed = BooleanField('Confirmed')
    # WTForms 对 HTML 表单控件 <select> 进行 SelectField 包装,从而实现下拉列表
    role = SelectField('角色', coerce=int)
    name = StringField('真实姓名', validators=[Length(0, 64)])
    location = StringField('地点', validators=[Length(0, 64)])
    about_me = TextAreaField('关于我')
    submit = SubmitField('提交')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        """
        SelectField 实例必须在其 choices 属性中设置各选项。
        选项必须是一个由元组组成的列表,各元组都包含两个元素:选项的标识符和显示在控件中的文本字符串。
        choices 列表在表单的构造函数中设定,其值从 Role 模型中获取,使用一个查询按照角色名的字母顺序排列所有角色。
        元组中的标识符是角色的 id,因为这是个整数,所以在 SelectField 构造函数中添加 coerce=int 参数,从而把字段的值转换为整数, 而不使用默认的字符串。
        """
        self.role.choices = [(role.id, role.name) for role in Role.query.order_by(Role.name).all()]
        self.user = user

    # 表单构造函数接收用户对象作为参数,并将其保存在成员变量中,随后自定义的验证方法要使用这个用户对象。
    def validate_email(self, field):
        if field.data != self.user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已被注册啦 ╮(￣▽￣)╭ ')

    def validate_username(self, field):
        if field.data != self.user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已被使用啦 ╮(￣▽￣)╭')


class PostForm(FlaskForm):
    # 若想把首页中的多行文本控件转换成 Markdown 富文本编辑器,PostForm 表单中的 body 字段要进行修改
    title = TextAreaField("编辑文章_标题", validators=[DataRequired()])
    intro = TextAreaField("编辑文章_简介")
    body = TextAreaField("编辑文章_正文", validators=[DataRequired()])
    body_html = TextAreaField("预览", validators=[DataRequired()])
    category = SelectField('分类', coerce=int)
    tags = TextAreaField("标签", validators=[DataRequired()])
    submit = SubmitField('发表文章')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.category.choices = [(cg.id, cg.category_name)
                                 for cg in Category.query.order_by(Category.category_name).all()]


class CommentForm(FlaskForm):
    body = PageDownField(
        '评论支持部分 Markdown 语法( <a href="https://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown 语法快速入门</a> )',
        validators=[DataRequired()])
    submit = SubmitField('提交')

app/blog/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function, unicode_literals, absolute_import
from flask import Blueprint, current_app, request

blog = Blueprint('blog', __name__, static_folder='static', template_folder='templates')

from . import views
from . import models
from urllib.parse import urljoin
from app import permissions


def url_for_cdn(filename):
    cdn_https = current_app.config.get('CDN_HTTPS', False)
    scheme = 'http'
    if cdn_https or request.is_secure:
        scheme = 'https'
    return urljoin(scheme + '://' + current_app.config['PUBLIC_CDN_DOMAIN'], filename)


@blog.app_context_processor
def inject_permissions():
    return dict(permissions=permissions, url_for_cdn=url_for_cdn)

app/blog/views/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function, unicode_literals, absolute_import

from . import home
from . import auth
from . import errors

app/blog/views/errors.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function, unicode_literals, absolute_import
from flask import render_template
from .. import blog


# 如果使用 errorhandler 修饰器,那么只有蓝本中的错误才能触发处理程序。
# 要想注册程序全局的错误处理程序,必须使用 app_errorhandler
@blog.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@blog.app_errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

app/blog/views/home.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function, unicode_literals, absolute_import
from flask import render_template, redirect, url_for, abort, flash, request, current_app, make_response
from flask_login import login_required, current_user
from flask_sqlalchemy import get_debug_queries
from app.blog.models import Role, User, Post, Comment, Category, HomePage, Tag
from app import db, cache
from .forms import EditProfileForm, EditProfileAdminForm, PostForm, CommentForm
from .. import blog
from app.permissions import permission_blogger, permission_admin


# 为会出现分类列表的排序做准备，涉及到路由'/post/<int:id>'、'/article'和'/article/<category_name>'
def sort_category():
    if Category.query.all():
        category = Category.query.all()
        dict_cg = {}
        for i in category:
            dict_cg[i] = i.posts.count()
        category = sorted(dict_cg, key=dict_cg.__getitem__, reverse=True)
        return category


# 报告缓慢的数据库查询
"""
这个功能使用 after_app_request 处理程序实现,它和 before_app_request 处理程序的工作方式类似,只不过在视图函数处理完请求之后执行。
Flask 把响应对象传给 after_app_ request 处理程序,以防需要修改响应。
在这里,after_app_request 处理程序没有修改响应,只是获取 Flask-SQLAlchemy 记录 的查询时间并把缓慢的查询写入日志。

"""


@blog.after_app_request
def after_request(response):
    """
    get_debug_queries() 函数返回一个列表,其元素是请求中执行的查询
    遍历 get_debug_queries() 函数获取的列表,把持续时间比设定阈值长的查询写入日志。
    写入的日志被设为“警告”等级。如果换成“错误”等级,发 现缓慢的查询时还会发送电子邮件。
    """
    for query in get_debug_queries():
        if query.duration >= current_app.config['FLASKY_SLOW_DB_QUERY_TIME']:
            current_app.logger.warning(
                'Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n'
                % (query.statement, query.parameters, query.duration, query.context))
    return response


"""
Werkzeug Web 服务器本身就有停止选项,但由于服务器运行在单独的线程中,
关闭服务器的唯一方法是发送一个普通的 HTTP 请求.

只有当程序运行在测试环境中时,这个关闭服务器的路由才可用,在其他配置中调用时将不起作用。
在实际过程中,关闭服务器时要调用 Werkzeug 在环境中提供的关闭函数。
调用这个函数且请求处理完成后,开发服务器就知道自己需要优雅地退出了。
"""


@blog.route('/shutdown')
def server_shutdown():
    if not current_app.testing:
        abort(404)
    shutdown = request.environ.get('werkzeug.server.shutdown')
    if not shutdown:
        abort(500)
    shutdown()
    return 'Shutting down...'


@blog.route('/', methods=['GET', 'POST'])
def index():
    homepages = HomePage.query.filter_by(id=1).first()
    if not homepages:
        homepages = HomePage(view_times=1)
        db.session.add(homepages)
        db.session.commit()
    try:
        if homepages.view_times > 0:
            homepages.view_times += 1
        else:
            homepages.view_times = 1
        db.session.add(homepages)
        db.session.commit()
    except:
        pass
    return render_template('index.html')


@blog.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
        # 用户发布的博客文章列表通过 User.posts 关系获取,User.posts 返回的是查询对象,
        # 因此可在其上调用过滤器,例如 order_by()。
    posts = user.posts.order_by(Post.post_date.desc()).all()
    return render_template('user.html', user=user, posts=posts)


@blog.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        db.session.commit()
        flash('资料已更新 (｡・`ω´･)')
        return redirect(url_for('.user', username=current_user.username))
    # 为所有字段设定了初始值
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)


@blog.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_blogger.require(403)
# 用户由 id 指定
def edit_profile_admin(id):
    # 使用 Flask-SQLAlchemy 提供的 get_or_404() 函数,如果提供的 id 不正确,则会返回 404 错误。
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        # user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.username = form.name.data
        # user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        flash('资料已更新 (｡・`ω´･)')
        return redirect(url_for('.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    # form.confirmed.data = user.confirmed
    form.role.data = user.roles[0].id
    form.name.data = user.username
    # form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('edit_profile.html', form=form, user=user)


# 博客文章的 URL 使用插入数据库时分配的唯一 id 字段构建
@blog.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get_or_404(id)
    post.body_show = True
    # 这个视图函数实例化了一个评论表单,并将其转入 post.html 模板,以便渲染。
    input_hint = '''### h3标题（注意：换行是先敲两个空格再敲回车！）  
***  
+ 三个星号是分隔线。现在这个加号后面一个空格是列表。  
+ *斜体*  
+  **粗体**  
+ `代码`  
+ [完整版 Markdown 语法说明](http://wowubuntu.com/markdown/index.html)  

> 块引用  

    # Python
    print "每行前面加四个空格是代码块"  
 '''
    form = CommentForm(body=input_hint)
    # 提交表单 后,插入新评论的逻辑和处理博客文章的过程差不多
    if form.validate_on_submit():
        # 和 Post 模型一样,评论的 author 字段也不能直接设为 current_user,因为这个变量是上下文代理对象。
        # 真正的 User 对象要 使用表达式 current_user._get_current_object() 获取。
        comment = Comment(body=form.body.data, post=post, author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        flash('评论已提交 (｡・`ω´･)')
        # 提交评论后,请求结果是一个重定 向,转回之前的 URL,但是在 url_for() 函数的参数中把 page 设为 -1,
        # 这是个特殊的页 数,用来请求评论的最后一页,所以刚提交的评论才会出现在页面中。
        return redirect(url_for('.post', id=post.id))
    # 程序从查询字符串 中获取页数,发现值为 -1 时,会计算评论的总量和总页数,得出真正要显示的页数。
    page = request.args.get('page', 1, type=int)
    if page == -1:
        # " // "来表示整数除法，返回不大于结果的一个最大的整数，而" / " 则单纯的表示浮点数除法
        page = (post.comments.count() - 1) // \
               current_app.config['FLASKY_COMMENTS_PER_PAGE'] + 1
    # 文章的评论列表通过 post.comments 一对多关系获取,按照时间戳顺序进行排列,再使 用与博客文章相同的技术分页显示。
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    category = sort_category()
    if post.view_times > 0:
        post.view_times += 1
    else:
        post.view_times = 1
    db.session.add(post)
    db.session.commit()
    # 评论列表对象和分页对象都传入了模板,以便渲染。
    return render_template('post.html', posts=[post], form=form, categories=category, comments=comments,
                           pagination=pagination)
    # 评论的渲染过程在新模板 _comments.html 中进行,类似于 _posts.html,但使用的 CSS 类不 同。
    # _comments.html 模板要引入 post.html 中,放在文章正文下方,后面再显示分页导航。

    """ 这是之前的最后一句：

    post.html 模板接收一个列表作为参数,这个列表就是要渲染的文章。
    这里必须要传入列表,因为只有这样,index.html 和 user.html 引用的 _posts.html 模板才能在这个页面中使用。

    return render_template('post.html', posts=[post])
    """


@blog.route('/edit/<int:id>', methods=['GET', 'POST'])
@permission_blogger.require(403)
def edit(id):
    post = Post.query.get_or_404(id)
    if post.category_id:
        category = Category.query.get_or_404(post.category_id)
    if current_user.id != post.author_id:
        abort(403)
    # 这里使用 的 PostForm 表单类和首页中使用的是同一个。
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.intro = form.intro.data
        post.body = form.body.data
        post.tags = [Tag.get_tag(t_n.strip()) for t_n in form.tags.data.split(',') if t_n]
        if form.category.data:
            category_name_exists = Category.query.filter_by(category_name=form.category.data).first()
            if not category_name_exists:
                category = Category(form.category.data)
                db.session.add(category)
                db.session.commit()
                post.category_id = category.id
            else:
                post.category_id = category_name_exists.id
        db.session.add(post)
        db.session.commit()
        flash('文章已提交 (｡・`ω´･)')
        return redirect(url_for('.post', id=post.id))
    form.title.data = post.title
    form.intro.data = post.intro
    form.body.data = post.body
    form.tags.data = ','.join([tag.name for tag in post.tags])
    if post.category_id:
        category = Category.query.filter_by(id=post.category.id).first()
        form.category.data = category.category_name
    return render_template('edit_post.html', form=form, post=post)


@blog.route('/all')
@login_required
def show_all():
    # cookie 只能在响应对象中设置,因此这两个路由不能依赖 Flask,要使用 make_response() 方法创建响应对象。
    resp = make_response(redirect(url_for('.article')))
    # set_cookie() 函数的前两个参数分别是 cookie 名和值。可选的 max_age 参数设置 cookie 的过期时间,单位为秒。
    # 如果不指定参数 max_age,浏览器关闭后 cookie 就会过期。
    resp.set_cookie('show_followed', '', max_age=30 * 24 * 60 * 60)
    return resp


@blog.route('/followed')
@login_required
def show_followed():
    resp = make_response(redirect(url_for('.article')))
    resp.set_cookie('show_followed', '1', max_age=30 * 24 * 60 * 60)
    return resp


# 管理评论的路由
# 这个函数很简单,它从数据库中读取一页评论,将其传入模板进行渲染。除了评论列表之外,还把分页对象和当前页数传入了模板。
@blog.route('/moderate')
@login_required
@permission_blogger.require(403)
def moderate():
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('moderate.html', comments=comments, pagination=pagination, page=page)


"""
以下启用路由和禁用路由都是先加载评论对象,把 disabled 字段设为正确的值,再把评论对象写入数据库。
最后,重定向到评论管理页面,如果查询字符串中指定了 page 参数,会将其传入重定向操作。

app/blog/templates/_article_sidebar.html
<div>
    <ul class="list-group">
        <li class="list-group-item list-group-item-danger ">
            <span class="glyphicon glyphicon-book"></span>
            <span>&nbsp;&nbsp;分类</span>
        </li>
        {% if categories %}
            {% for category in categories %}
                {# if category.posts.count() > 0 #}
                <a href="{{ url_for('.article_category_name', category_name=category.category_name) }}" class="list-group-item">
                    {{ category.category_name }}
                    <span class="badge">{{ category.posts.count() }}</span>
                </a>
                {# endif #}
            {% endfor %}
        {% endif %}
    </ul>
</div>

app/blog/templates/_macros.html
<!-- 
Flask-SQLAlchemy分页对象拥有强大的对象和 Bootstrap 中的分页 CSS 类,能够很轻易地就能在模板底部构建一个分页导航。
于是现在这个 Jinja2 宏的形式实现的分页导航。
这个宏创建了一个 Bootstrap 分页元素,即一个有特殊样式的无序列表
 -->

 <!-- pagination_widget 宏可放在 index.html 和 user.html 中的 _posts.html 模板后面 -->

<!-- Jinja2 宏的参数列表中不用加入 **kwargs 即可接收关键字参数。分页宏把接收到的所有关键字参数都传给了生成分页链接的 url_for() 方法。 -->
<!-- 13.2节：分页导航所用的宏也要做些改动。评论的分页导航链接也要加上 #comments 片段,因此在 post.html 模板中调用宏时,传入片段参数。于是下面的fragment=''和{{ fragment }}都是新增的 -->
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <!-- “上一页”链接。如果当前页是第一页,则为这个链接加上 disabled 类,禁用这个链接。 -->
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>

    <!--
    分页对象的iter_pages()迭代器返回的所有页面链接。
    这些页面被渲染成具有明确页数的链接,页数在 url_for() 的参数中指定。
    当前显示的页面使用 activeCSS 类高亮显示。
    页数列表中的间隔使用省略号表示。
    -->
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    
    <!-- “下一页”链接。如果当前页是最后一页,则为这个链接加上 disabled 类,禁用这个链接。 -->
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/blog/templates/base.html
{% extends "bootstrap/base.html" %}

{% macro show_title() -%}
OAOA的小站
{%- endmacro %}

{% block title %}{{ show_title() }}{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('blog.static', filename='img/favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block metas %}
{{ super() }}
<meta charset="UTF-8">
{% endblock %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('blog.static', filename='css/styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('blog.index') }}">五迷之家</a>
        </div>
        <div class="navbar-collapse collapse">
            <div id="cd-nav">
                <a href="#0" class="cd-nav-trigger">Menu<span></span></a>
                <div id="cd-main-nav">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('blog.index') }}">主页</a></li>
                        <!-- 把资料页面的链接包含在条件语句中是非常必要的,因为未认证的用户也能看到导航条,但我们不应该让他们看到资料页面的链接。 -->
                        <li><a href="{{ url_for('blog.article') }}">博客</a></li>
                        <li><a href="{{ url_for('blog.resume') }}">个人简历</a></li>
                        <li><a href="{{ url_for('blog.lab') }}">实验室</a></li>
                        <li><a href="{{ url_for('blog.contact') }}">关于</a></li>
                        {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('blog.user', username=current_user.username) }}">PROFILE</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <!-- 为了管理评论我们要在导航条中添加一个链接具有权限的用户才能看到。这个链接在base.html 模板中使用条件语句添加 -->
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('blog.moderate') }}">管理评论</a></li>
                {% endif %}
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img class="img-rounded navbar-avatar" id="user_avatar_thumb"
                             src="{# url_for('blog.static', filename='img/favicon.ico') #}">
                        {{ current_user.username }} <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('blog.change_password') }}">修改密码</a></li>
                        <li><a href="{{ url_for('blog.logout') }}">退出</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('blog.login') }}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% block page_content %}{% endblock %}
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{ url_for_cdn('modernizr/2.8.3/modernizr.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for_cdn('identicon.js/2.1.0/pnglib.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for_cdn('identicon.js/2.1.0/identicon.min.js') }}"></script>
{{ moment.include_moment(local_js=url_for_cdn('moment.js/2.18.1/moment.min.js')) }}
{{- moment.lang('zh-cn') -}}
{{ pagedown.include_pagedown() }}

<script type="text/javascript">
    var user_avatar_thumb = $("#user_avatar_thumb")[0];
    if(user_avatar_thumb)
    {
        var data = new Identicon('{{ current_user.avatar }}', 40).toString();
        user_avatar_thumb.src='data:image/png;base64,' + data;
    }
</script>
{% endblock %}

app/blog/templates/edit_post.html
{% extends "base.html" %}
{# import "bootstrap/wtf.html" as wtf #}

{% block title %}{{ show_title() }} - 编辑文章{% endblock %}

{%- block head %}
{{ super() }}
<style type="text/css">
    #flask-pagedown-body {
        height: 260px;
    }

</style>
<link rel="stylesheet" type="text/css"
      href="{{ url_for('blog.static', filename='editor.md/css/editormd.min.css') }}">
<link rel="stylesheet" type="text/css"
      href="{{ url_for('blog.static', filename='editor.md/css/editormd.preview.min.css') }}">
{% endblock -%}

{%- block page_content %}
<div class="container-fluid">
    <div class="page-header">
        <h1>编辑文章</h1>
    </div>
    <div class="write-article-body">
        {% if current_user.is_blogger %}
        {#
        <div class="form-write-article">{{ wtf.quick_form(form) }}</div>
        #}
        <div class="col-md-11" style="margin-bottom: 20px;margin-left: 100px;" id="article_new">
            <form action="{{url_for('blog.edit', id=post.id)}}" method="post" class="form-group">
                <div style="display: none">
                    {{ form.csrf_token() }}
                </div>
                <div class="form-group">
                    <label for="title">文章标题</label>
                    {{ form.title(id='title', class="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.intro(id = 'intro', class='form-control', placeholder='文章摘要') }}
                </div>
                <div class="form-group">
                    <label for="editormd-view">文章内容</label>
                    <div id="editormd-view">
                        {{ form.body(id='body') }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="category_name">文章分类</label>
                    {{ form.category(id='category_name', class="form-control") }}
                </div>
                <div class="form-group">
                    <label class="control-label" for="tags">文章标签</label>
                    <div class="input-group">
                        {{form.tags(id="tags", placeholder="以,分隔", class="form-control input-md", required="")}}
                    </div>
                </div>
                <div class="form-group" style="display: inline">
                    {{ form.submit(id='abc', class='btn btn-default') }}
                </div>
                <div style="display: none;">
                    {{ form.body_html(id='body_html') }}
                </div>
            </form>
        </div>
        {% endif %}
    </div>
</div>
{% endblock -%}

{% block scripts %}
{{ super() }}
{{- pagedown.include_pagedown() -}}
<script src="{{ url_for('blog.static', filename='editor.md/editormd.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">
        $(document).ready( function() {
            var editor = editormd("editormd-view", {
                path : "{{url_for('blog.static', filename='editor.md/lib/')}}" ,// Autoload modules mode, dependents libs path
                pluginPath: "{{url_for('blog.static', filename='editor.md/plugins/')}}",
                height : 640,
    {#            width: "90%",#}
                theme : "dark",
    {#            previewTheme : "dark",#}
                codeFold : true,
                syncScrolling : "single",
    {#            htmlDecode : "style,script,iframe|on*",            // 开启 HTML 标签解析，为了安全性，默认不开启#}
                emoji : true,
                taskList : true,
                tocm            : true,         // Using [TOCM]
                tex : true,                   // 开启科学公式TeX语言支持，默认关闭
                flowChart : true,             // 开启流程图支持，默认关闭
                sequenceDiagram : true,       // 开启时序/序列图支持，默认关闭,
                imageUpload : true,
                saveHTMLToTextarea: true  // 用于将解析后的 HTML 保存到 Textarea，以供提交到后台程序
            });
            editor.setToolbarAutoFixed(false);  // toolbar 自动调位 禁用

            $('#abc').click(function () {
                //var msg = $('.editormd-preview').html()
                $('#body_html').val(editor.getHTML())
            });

        });

</script>
{% endblock %}